export function getMockSearchResponse(numberOfResults = 6, searchTerm = "ti") {
  return {
    results: {
      isGooglePowered: false,
      docs: [
        {
          country: "France",
          lng: 2.11278,
          city: "Paris",
          searchType: "L",
          alternative: ["FR,Beauvais Tille"],
          index: 1,
          bookingId: "airport-8266",
          placeType: "A",
          placeKey: "1472099",
          iata: "BVA",
          countryIso: "fr",
          locationId: "8266",
          name: "Beauvais Airport",
          ufi: 900038821,
          isPopular: false,
          region: "Ile de France",
          lang: "en",
          lat: 49.4544,
        },
        {
          country: "Austria",
          lng: 11.3936,
          searchType: "L",
          alternative: ["AT"],
          index: 2,
          bookingId: "city-128314",
          placeType: "C",
          placeKey: "27681",
          countryIso: "at",
          locationId: "1696",
          name: "Innsbruck",
          ufi: -1981445,
          isPopular: false,
          region: "Tirol",
          lang: "en",
          lat: 47.2667,
        },
        {
          country: "Switzerland",
          lng: 8.94927,
          searchType: "L",
          alternative: ["CH,Lake Lugano,Lugano"],
          index: 3,
          bookingId: "city-2457834",
          placeType: "C",
          placeKey: "156537",
          countryIso: "ch",
          locationId: "19296",
          name: "Lugano",
          ufi: -2552969,
          isPopular: false,
          region: "Ticino",
          lang: "en",
          lat: 46.0047,
        },
        {
          country: "Switzerland",
          lng: 8.91027,
          city: "Lugano",
          searchType: "L",
          alternative: ["CH,Lake Lugano,Lugano,Agno"],
          index: 4,
          bookingId: "airport-33871",
          placeType: "A",
          placeKey: "1471912",
          iata: "LUG",
          countryIso: "ch",
          locationId: "33871",
          name: "Lugano Airport",
          ufi: 900038863,
          isPopular: false,
          region: "Ticino",
          lang: "en",
          lat: 46.0037,
        },
        {
          country: "Italy",
          lng: 15.6504,
          city: "Reggio di Calabria",
          searchType: "L",
          alternative: ["IT,Tito Menniti"],
          index: 5,
          bookingId: "airport-22001",
          placeType: "A",
          placeKey: "1472310",
          iata: "REG",
          countryIso: "it",
          locationId: "22001",
          name: "Reggio Airport",
          ufi: 900039761,
          isPopular: false,
          region: "Calabria",
          lang: "en",
          lat: 38.0745,
        },
        {
          country: "Montenegro",
          lng: 18.7233,
          city: "Tivat",
          searchType: "L",
          alternative: [
            "ME,Adriatic Coast,Kotor Bay,Montenegro Coast,Tivat Riviera,Aerodrom Tivat",
          ],
          index: 6,
          bookingId: "airport-25836",
          placeType: "A",
          placeKey: "1472420",
          iata: "TIV",
          countryIso: "me",
          locationId: "25836",
          name: "Tivat Airport",
          ufi: 900039788,
          isPopular: false,
          region: "Tivat County",
          lang: "en",
          lat: 42.4044,
        },
      ],
      numFound: 13912,
    },
  };
}
